# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 756fb9ef74182df65e445657dad2391b98a5237134044e23c9ac8bccc0a41323ce3bbcb6327685c98e46945ffe8ad02852cb8319b3956562251340a3a2d30801
  bart_api_key: Q2VM-UGUU-I4PQ-DT35

test:
  secret_key_base: ffa57fc27db38052dec6f1deda86220a66e3ded8e0b46f228f97aa27927445570bc38e8193ae9ca0b2cdf62de4e3b1fe1538e759863f773a1faa695bd45ed855
  bart_api_key: Q2VM-UGUU-I4PQ-DT35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
